import ProjectDescription
import ProjectDescriptionHelpers

let workspace = Workspace(
  name: ProjectConfig.name,
  projects: [
    "Projects/App"
  ],
  additionalFiles: [
    "swiftlint.yml"
  ],
  generationOptions: .options(
    autogeneratedWorkspaceSchemes: .disabled,
    lastXcodeUpgradeCheck: "26.2"
  )
)
